#############################################################################
# Makefile for building: fluidlauncher
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  fluidlauncher.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile fluidlauncher.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NO_QML_DEBUGGER -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -mcpu=cortex-a9 -marm -mfloat-abi=hard --sysroot=/opt/rootfs-s5p4418 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -pipe -mcpu=cortex-a9 -marm -mfloat-abi=hard --sysroot=/opt/rootfs-s5p4418 -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtWidgets -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQuick -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtGui -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQml -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtNetwork -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtCore -I. -I/usr/nexell-libs/include/khronos/GLES2 -I/usr/nexell-libs/include/khronos -I/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = fluidlauncher1.0.0
DISTDIR = /home/ubuntu/share/nanoPi_Mes/fluidlauncher/.tmp/fluidlauncher1.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -fuse-ld=gold -mfloat-abi=hard --sysroot=/opt/rootfs-s5p4418 -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-5.10.0-nexell32/lib
LIBS          = $(SUBLIBS) -L/usr/nexell-libs/lib32 -L/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/lib -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = demoapplication.cpp \
		fluidlauncher.cpp \
		main.cpp \
		pictureflow.cpp \
		slideshow.cpp moc_demoapplication.cpp \
		moc_fluidlauncher.cpp \
		moc_pictureflow.cpp \
		moc_slideshow.cpp
OBJECTS       = demoapplication.o \
		fluidlauncher.o \
		main.o \
		pictureflow.o \
		slideshow.o \
		moc_demoapplication.o \
		moc_fluidlauncher.o \
		moc_pictureflow.o \
		moc_slideshow.o
DIST          = /usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/spec_pre.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/sanitize.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/qdevice.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/device_config.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++/qmake.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/toolchain.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/resolve_config.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qmake_use.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/file_copies.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/testcase_targets.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/exceptions.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/lex.prf \
		fluidlauncher.pro demoapplication.h \
		fluidlauncher.h \
		pictureflow.h \
		slideshow.h demoapplication.cpp \
		fluidlauncher.cpp \
		main.cpp \
		pictureflow.cpp \
		slideshow.cpp
QMAKE_TARGET  = fluidlauncher
DESTDIR       = 
TARGET        = fluidlauncher


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fluidlauncher.pro /usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++/qmake.conf /usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/spec_pre.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/sanitize.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/qdevice.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/device_config.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++/qmake.conf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/toolchain.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/resolve_config.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qmake_use.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/file_copies.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/testcase_targets.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/exceptions.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/lex.prf \
		fluidlauncher.pro
	$(QMAKE) -o Makefile fluidlauncher.pro
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/spec_pre.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/sanitize.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/qdevice.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/device_config.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_device_pre.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_device_post.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/common/linux_arm_device_post.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_core.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_help.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_location.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_network.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_script.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++/qmake.conf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/toolchain.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/resolve_config.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/unix/opengl.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/qmake_use.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/file_copies.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/testcase_targets.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/exceptions.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/lex.prf:
fluidlauncher.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile fluidlauncher.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents demoapplication.h fluidlauncher.h pictureflow.h slideshow.h $(DISTDIR)/
	$(COPY_FILE) --parents demoapplication.cpp fluidlauncher.cpp main.cpp pictureflow.cpp slideshow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/data/dummy.cpp
	arm-linux-gnueabihf-g++ -pipe -pipe -mcpu=cortex-a9 -marm -mfloat-abi=hard --sysroot=/opt/rootfs-s5p4418 -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_demoapplication.cpp moc_fluidlauncher.cpp moc_pictureflow.cpp moc_slideshow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_demoapplication.cpp moc_fluidlauncher.cpp moc_pictureflow.cpp moc_slideshow.cpp
moc_demoapplication.cpp: demoapplication.h \
		moc_predefs.h \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/bin/moc
	/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++ -I/home/ubuntu/share/nanoPi_Mes/fluidlauncher -I/home/ubuntu/share/nanoPi_Mes/fluidlauncher -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtWidgets -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQuick -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtGui -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQml -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtNetwork -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtCore -I/usr/arm-linux-gnueabihf/include/c++/5 -I/usr/arm-linux-gnueabihf/include/c++/5/arm-linux-gnueabihf -I/usr/arm-linux-gnueabihf/include/c++/5/backward -I/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include -I/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include-fixed -I/usr/arm-linux-gnueabihf/include demoapplication.h -o moc_demoapplication.cpp

moc_fluidlauncher.cpp: pictureflow.h \
		slideshow.h \
		demoapplication.h \
		fluidlauncher.h \
		moc_predefs.h \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/bin/moc
	/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++ -I/home/ubuntu/share/nanoPi_Mes/fluidlauncher -I/home/ubuntu/share/nanoPi_Mes/fluidlauncher -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtWidgets -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQuick -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtGui -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQml -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtNetwork -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtCore -I/usr/arm-linux-gnueabihf/include/c++/5 -I/usr/arm-linux-gnueabihf/include/c++/5/arm-linux-gnueabihf -I/usr/arm-linux-gnueabihf/include/c++/5/backward -I/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include -I/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include-fixed -I/usr/arm-linux-gnueabihf/include fluidlauncher.h -o moc_fluidlauncher.cpp

moc_pictureflow.cpp: pictureflow.h \
		moc_predefs.h \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/bin/moc
	/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++ -I/home/ubuntu/share/nanoPi_Mes/fluidlauncher -I/home/ubuntu/share/nanoPi_Mes/fluidlauncher -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtWidgets -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQuick -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtGui -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQml -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtNetwork -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtCore -I/usr/arm-linux-gnueabihf/include/c++/5 -I/usr/arm-linux-gnueabihf/include/c++/5/arm-linux-gnueabihf -I/usr/arm-linux-gnueabihf/include/c++/5/backward -I/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include -I/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include-fixed -I/usr/arm-linux-gnueabihf/include pictureflow.h -o moc_pictureflow.cpp

moc_slideshow.cpp: slideshow.h \
		moc_predefs.h \
		/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/bin/moc
	/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Trolltech/Qt-5.10.0-nexell32-sdk/mkspecs/devices/linux-friendlyelec-nexell32-g++ -I/home/ubuntu/share/nanoPi_Mes/fluidlauncher -I/home/ubuntu/share/nanoPi_Mes/fluidlauncher -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtWidgets -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQuick -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtGui -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtQml -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtNetwork -I/opt/rootfs-s5p4418/usr/local/Trolltech/Qt-5.10.0-nexell32/include/QtCore -I/usr/arm-linux-gnueabihf/include/c++/5 -I/usr/arm-linux-gnueabihf/include/c++/5/arm-linux-gnueabihf -I/usr/arm-linux-gnueabihf/include/c++/5/backward -I/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include -I/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include-fixed -I/usr/arm-linux-gnueabihf/include slideshow.h -o moc_slideshow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

demoapplication.o: demoapplication.cpp demoapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o demoapplication.o demoapplication.cpp

fluidlauncher.o: fluidlauncher.cpp fluidlauncher.h \
		pictureflow.h \
		slideshow.h \
		demoapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fluidlauncher.o fluidlauncher.cpp

main.o: main.cpp fluidlauncher.h \
		pictureflow.h \
		slideshow.h \
		demoapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pictureflow.o: pictureflow.cpp pictureflow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pictureflow.o pictureflow.cpp

slideshow.o: slideshow.cpp slideshow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slideshow.o slideshow.cpp

moc_demoapplication.o: moc_demoapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_demoapplication.o moc_demoapplication.cpp

moc_fluidlauncher.o: moc_fluidlauncher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fluidlauncher.o moc_fluidlauncher.cpp

moc_pictureflow.o: moc_pictureflow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pictureflow.o moc_pictureflow.cpp

moc_slideshow.o: moc_slideshow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_slideshow.o moc_slideshow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

